steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/android-build/android-sdk:latest']
  - name: 'gcr.io/android-build/android-sdk'
    args: ['bash', './setup-android-sdk.sh']
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['build']
    dir: 'source'
timeout: 1800s
options:
  machineType: 'E2_HIGHCPU_8'